`timescale 1ns / 1ps

module tb_bcd_to_7seg;

reg  [3:0] i_bcd  ;

wire [6:0] o_seg  ;

bcd_to_7seg uut (
	.i_bcd(i_bcd),
	.o_seg(o_seg)
);

initial begin
	$dumpfile("./bcd_to_7seg.vcd");
	$dumpvars(0, tb_bcd_to_7seg  );
end

initial begin
	$monitor("Time=%0t | i_bcd Input=%b | Seven Segment output=%b", $time, i_bcd, o_seg);

	i_bcd = 4'b0000; #10;
	i_bcd = 4'b0001; #10;
	i_bcd = 4'b0010; #10;
	i_bcd = 4'b0011; #10;
	i_bcd = 4'b0100; #10;
	i_bcd = 4'b0101; #10;
	i_bcd = 4'b0110; #10;
	i_bcd = 4'b0111; #10;
	i_bcd = 4'b1000; #10;
	$finish;

end
endmodule 
